'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { apiRequest } from '../../../lib/api';
type Item = { id: string; name: string; sizeBytes?: string; mimeType?: string };
type Content = { roomName: string; folders?: Item[]; files?: Item[]; file?: Item & { url: string; downloadUrl: string } };
export default function PublicSharePage() {
  const { token } = useParams<{ token: string }>(); const [root, setRoot] = useState<{ resourceType: 'DATA_ROOM' | 'FOLDER'; resourceId: string }>(); const [path, setPath] = useState<Item[]>([]); const [content, setContent] = useState<Content>(); const [error, setError] = useState('Loading shared resource…');
  async function load(type: 'DATA_ROOM' | 'FOLDER', id: string) { try { setError(''); setContent(await apiRequest<Content>(`/shares/public/${token}/content?resourceType=${type}&resourceId=${id}`)); } catch (e) { setError(e instanceof Error ? e.message : 'Share unavailable'); } }
  useEffect(() => { apiRequest<{ resourceType: 'DATA_ROOM' | 'FOLDER'; resourceId: string }>(`/shares/public/${token}`).then((r) => { setRoot(r); void load(r.resourceType, r.resourceId); }).catch((e) => setError(e instanceof Error ? e.message : 'Share unavailable')); }, [token]);
  const openFile = async (id: string) => { const result = await apiRequest<Content>(`/shares/public/${token}/content?resourceType=FILE&resourceId=${id}`); setContent(result); };
  return <main className="app-shell"><header><div><p className="eyebrow">PUBLIC DATA ROOM</p><h1>{content?.roomName ?? 'Shared Data Room'}</h1></div></header>{error ? <p>{error}</p> : content?.file ? <section><button type="button" onClick={() => { const parent = path.at(-1); if (parent) void load('FOLDER', parent.id); else if (root) void load(root.resourceType, root.resourceId); }}>← Back to folder</button><h2>{content.file.name}</h2><p>{content.file.sizeBytes} bytes</p>{content.file.mimeType === 'application/pdf' && <iframe title={content.file.name} src={content.file.url} style={{ width: '100%', minHeight: 650 }} />}<p><a href={content.file.downloadUrl}>Download</a></p></section> : <><nav><button type="button" onClick={() => { if (root) { setPath([]); void load(root.resourceType, root.resourceId); } }}>Root</button>{path.map((p, i) => <span key={p.id}> / <button type="button" onClick={() => { setPath(path.slice(0, i + 1)); void load('FOLDER', p.id); }}>{p.name}</button></span>)}</nav><ul className="folder-list">{content?.folders?.map((f) => <li key={f.id}><button type="button" onClick={() => { setPath([...path, f]); void load('FOLDER', f.id); }}>📁 {f.name}</button></li>)}{content?.files?.map((f) => <li key={f.id}><button type="button" onClick={() => void openFile(f.id)}>📄 {f.name}</button></li>)}</ul>{!content?.folders?.length && !content?.files?.length && <p>This folder is empty.</p>}</>}</main>;
}
